#!/usr/bin/bash


#-------SUM METHOD TESTing--------------
: <<'END_COMMENT'
while [ true ]; do
    
    #random--0/1 decimals
    num1=$(printf -- "1.%d\n" $(od -An -N4 -t u4 < /dev/urandom))
    num2=$(printf -- "1.%d\n" $(od -An -N4 -t u4 < /dev/urandom))
    
    string="empty"
    string=$(echo "$num1 + $num2" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
    
    
    javastring="$(java -jar build/dist/*.jar $num1 $num2)"
    
    echo "calculating $num1 + $num2  |$string|  |$javastring|"
    if [[ $javastring != $string ]]; then
        echo "broken at"
        echo "$num1 + $num2"
        echo "bash says $string"
        echo "java says $javastring"
        break;
    fi

done
END_COMMENT


##----COMPARE METHOD TESTing--------------------
##(printf "%d.%d\n" $(od -An -N4 -i < /dev/urandom) $(od -An -N4 -t u4 < /dev/urandom)##

while [ true ]; do
    sign1="$(od -An -N4 -i < /dev/urandom | awk '{print substr($0,2,1)}')"
    sign2="$(od -An -N4 -i < /dev/urandom | awk '{print substr($0,2,1)}')"
    format1=""$sign1"0"
    format2=""$sign2"0"
    #random--0/1 decimals
    num1=$(printf -- "%d.%d\n" $(od -An -N4 -i < /dev/urandom) $(od -An -N4 -t u4 < /dev/urandom))
    num2=$(printf -- "%d.%d\n" $(od -An -N4 -i < /dev/urandom) $(od -An -N4 -t u4 < /dev/urandom))
    #-----others------------
    #num1=$(printf -- "%d.%d\n" $(od -An -N4 -i < /dev/urandom) $(od -An -N4 -t u4 < /dev/urandom))
    #num2=$(printf -- "%d.%d\n" $(od -An -N4 -i < /dev/urandom) $(od -An -N4 -t u4 < /dev/urandom))
    #-----------------------
    string="empty"
    if (( $(echo "$num1 > $num2" |bc -l) )); then
        string="true"
    else
        string="false"
    fi
    
    javastring="$(java -jar build/dist/*.jar $num1 $num2)"
    
    echo "calculating $num1 > $num2  |$string|  |$javastring|"
    if [[ $javastring != $string ]]; then
        echo "broken at"
        echo "$num1 > $num2"
        echo "bash says $string"
        echo "java says $javastring"
        break;
    fi

done


